### ISSUE TITLE
Need to add

### ISSUE THREAD

**Issue by jsm13** [jmas13/ga-js-ps#1]
Hey @recursivefunk @jshawl,

Is it tomorrow we need this? Right now it works (deployed to heroku and mLab db). Pretty good documentation linked but I will write an intro before whenever we need it. Would you let me know anything else to add?
- [ ] Readme

**Comment by jshawl** [comment]
not needed till next week! but thanks for setting this up!

On Tue, Apr 26, 2016 at 3:28 PM, John Master notifications@github.com
wrote:

> Hey @recursivefunk https://github.com/recursivefunk @jshawl
> https://github.com/jshawl,
> 
> Is it tomorrow we need this? Right now it works (deployed to heroku and
> mLab db). Pretty good documentation linked but I will write an intro before
> whenever we need it. Would you let me know anything else to add?
> - Readme
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jmas13/ga-js-ps/issues/1

## 

Jesse Shawl
http://jshawl.com

**Comment by recursivefunk** [comment]
Thanks! @jmas13
